updated for raven

diff --git a/scripts/debian/postinst b/scripts/debian/postinst
--- a/scripts/debian/postinst
+++ b/scripts/debian/postinst
@@ -3,35 +3,35 @@ set -e
 set -o pipefail
 
 # add group
-if ! getent group | grep -q "^bitcore:" ; then
-    echo "Creating system group: bitcore"
-    groupadd --system bitcore
+if ! getent group | grep -q "^ravencore:" ; then
+    echo "Creating system group: ravencore"
+    groupadd --system ravencore
 fi
 
 # add user
-if ! getent passwd | grep -q "^bitcore:"; then
-    echo "Creating bitcore system user"
-    useradd --gid "bitcore" --system -m bitcore
+if ! getent passwd | grep -q "^ravencore:"; then
+    echo "Creating ravencore system user"
+    useradd --gid "ravencore" --system -m ravencore
 fi
 
 # build nodejs addons
-cd "/usr/opt/bitcore"
+cd "/usr/opt/ravencore"
 SKIP_BITCOIN_DOWNLOAD=1 npm rebuild
 
 # setup data directory
-mkdir -p "/home/bitcore/.bitcore/data"
-chown -R bitcore:bitcore "/home/bitcore/.bitcore"
+mkdir -p "/home/ravencore/.ravencore/data"
+chown -R ravencore:ravencore "/home/ravencore/.ravencore"
 
-# start bitcore
+# start ravencore
 if hash service 2> /dev/null; then
-    service bitcore start || echo "bitcore could not be registered or started"
+    service ravencore start || echo "ravencore could not be registered or started"
 elif hash start 2> /dev/null; then
-    start bitcore || echo "bitcore could not be registered or started"
+    start ravencore || echo "ravencore could not be registered or started"
 elif hash systemctl 2> /dev/null; then
     {
-        systemctl enable "bitcore.service" && \
-            systemctl start "bitcore.service"
-    } || echo "bitcore could not be registered or started"
+        systemctl enable "ravencore.service" && \
+            systemctl start "ravencore.service"
+    } || echo "ravencore could not be registered or started"
 else
-    echo 'Your system does not appear to use upstart or systemd, so bitcore could not be started'
+    echo 'Your system does not appear to use upstart or systemd, so ravencore could not be started'
 fi
diff --git a/scripts/debian/prerm b/scripts/debian/prerm
--- a/scripts/debian/prerm
+++ b/scripts/debian/prerm
@@ -4,11 +4,11 @@ set -e
 set -o pipefail
 
 if hash service 2> /dev/null; then
-    service bitcore stop || echo "bitcore wasn't running!"
+    service ravencore stop || echo "ravencore wasn't running!"
 elif hash stop 2> /dev/null; then
-    stop "$service_name" || echo "bitcore wasn't running!"
+    stop "$service_name" || echo "ravencore wasn't running!"
 elif hash systemctl 2> /dev/null; then
-    systemctl disable "bitcore.service" || echo "bitcore wasn't running!"
+    systemctl disable "ravencore.service" || echo "ravencore wasn't running!"
 else
-    echo "Your system does not appear to use upstart or systemd, so bitcore could not be stopped"
+    echo "Your system does not appear to use upstart or systemd, so ravencore could not be stopped"
 fi
